version: "3.9"
services:
  web1:
    build: ./app
    image: main1
    container_name: cont1
    ports:
      - "8000:8080"
  web2:
    build: ./app2
    image: main2
    container_name: cont2
    ports:
      - "5000:8080"