FROM python:3.7

LABEL maintainer="Hanish"

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt

EXPOSE 8080

# command to run on container start
CMD ["uvicorn", "main2:app", "--host", "0.0.0.0", "--port", "8080"]
